config/routes.rb
VoterRegistration::Engine.routes.draw do
  
  #scope :module => :voter_registration do
    resources :guidelines, :only => [:index,:show], :as => 'guidelines'

    match '/register', :to => 'register#index', :as => 'register_index'
    post '/register/:state', :to => 'register#create', :as => 'register_create'
    match '/register/:state', :to => 'register#new', :as => 'register_new'
    match '/register/:state/complete', :to => 'register#complete', :as => 'register_complete'

    match '/auth/:provider/callback', to: 'sessions#create'
    match '/auth/failure', to: 'sessions#error'

    match '/:id' => 'high_voltage/pages#show', :as => :static, :via => :get

    root :to => 'home#index'
  #end
end

app/models/ethnicity.rb
class Ethnicity < ActiveRecord::Base
  attr_accessible :name
end

app/models/guidelines.rb
class Guidelines < ActiveRecord::Base
  attr_accessible :deadline, :early_voting, :felony, :identification, :locale, :requirements, :same_day, :state, :student, :url,
     :mail_to_address_1, :mail_to_address_2, :mail_to_address_3, :mail_to_address_4, :name, :online, :online_requirements, :online_url,
     :supported, :unsupported

  default_scope order("name")
end

app/models/instructions.rb
class Instructions < ActiveRecord::Base
  attr_accessible :help_text, :locale, :name, :required, :state
end

app/models/political_party.rb
class PoliticalParty < ActiveRecord::Base
  attr_accessible :name
  default_scope order("name")
end

app/models/register.rb
class Register
  include ActiveAttr::Model

  attribute :citizen
  attribute :title
  attribute :first_name
  attribute :middle_name
  attribute :last_name
  attribute :name_suffix
  attribute :home_address
  attribute :home_apt
  attribute :home_city
  attribute :home_state
  attribute :home_zip_code
  attribute :mailing_address
  attribute :mailing_apt
  attribute :mailing_city
  attribute :mailing_state
  attribute :mailing_zip_code
  attribute :previous_address
  attribute :previous_apt
  attribute :previous_city
  attribute :previous_state
  attribute :previous_zip_code
  attribute :previous_title
  attribute :previous_first_name
  attribute :previous_middle_name
  attribute :previous_last_name
  attribute :previous_suffix
  attribute :date_of_birth
  attribute :phone
  attribute :id_number
  attribute :political_party
  attribute :ethnicity

  attr_accessible :citizen, :title, :first_name, :middle_name, :last_name, :home_address, :home_apt, :home_city, :home_state, :home_zip_code,
                :mailing_address, :mailing_apt, :mailing_city, :mailing_state, :mailing_zip_code, :previous_address, :previous_apt,
                :previous_city, :previous_state, :previous_zip_code, :previous_title, :previous_first_name, :previous_middle_name,
                :previous_last_name, :date_of_birth, :phone, :id_number, :political_party, :ethnicity, :name_suffix, :previous_suffix

  validates_presence_of :title, :first_name, :last_name, :home_address, :home_city, :home_state, :home_zip_code, :date_of_birth, :id_number

end

app/controllers/voter_registration/application_controller.rb
module VoterRegistration
  class ApplicationController < ActionController::Base
    protect_from_forgery

    before_filter :set_locale

    def set_locale
      I18n.locale = params[:locale] || I18n.default_locale
    end

  end
end

app/controllers/voter_registration/guidelines_controller.rb
module VoterRegistration
  class GuidelinesController < VoterRegistration::ApplicationController
    def index
      @states = Guidelines.all
    end

    def show
      @guidelines = Guidelines.find_by_state(params[:id])

      if @guidelines.nil?
        redirect_to guidelines_path, :alert => "Invalid state"
      end

    end

  end
end

app/controllers/voter_registration/home_controller.rb
module VoterRegistration
  class HomeController < VoterRegistration::ApplicationController
    def index
      if params[:state]
        redirect_to vote.register_new_path(params[:state])
      end
    end
  end
end

app/controllers/voter_registration/register_controller.rb
module VoterRegistration
  class RegisterController < VoterRegistration::ApplicationController
    def index
      unless params[:state].blank?
        redirect_to vote.register_new_path(params[:state])
      end

    end

    def new

      session[:register] = nil
      @guidelines = Guidelines.find_by_state(params[:state])
      @state = params[:state]


      if @guidelines.nil?
        redirect_to register_index_path, :alert => "Invalid State"
      else
        @instructions = Instructions.where(:state => @state)
        if session[:user].nil?
          @register = Register.new
        else
          auth = session[:user]
          name = auth.info.name.split
          @register = Register.new(:first_name => name[0], :last_name => name[1], :home_city => auth.info.location)
        end
      end
    end

    def create
      birth_date = Date.strptime("#{params[:register]['date_of_birth(2i)']}/#{params[:register]['date_of_birth(3i)']}/#{params[:register]['date_of_birth(1i)']}", '%m/%d/%Y')
      #Assembling the multi parameter because active_attr doesn't support this yet
      #see - https://github.com/cgriego/active_attr/issues/9

      @register = Register.new(params[:register].merge(:date_of_birth => birth_date))
      @state = params[:state]

      if @register.valid?
        session[:register] = @register
        redirect_to register_complete_path(@register.home_state), :notice => "Registration Complete"
      else
        @guidelines = Guidelines.find_by_state(@state)
        @instructions = Instructions.where(:state => @state)
        render :action => 'new'
      end
    end

    def complete

      if session[:register].blank?
        redirect_to root_path
      else
        @register = session[:register]
        @state_info = Guidelines.find_by_state(@register.home_state)

        respond_to do |format|
          format.html
          format.pdf do
            pdf = RegistrationPdf.new(@register, @state_info, view_context)
            send_data pdf.render, filename: "voter_registration.pdf",
              type: "application/pdf",
              disposition: "attachment"
          end
        end
      end
    end
  end
end

app/helpers/voter_registration/application_helper.rb
module VoterRegistration
  module ApplicationHelper
  end
end

app/helpers/voter_registration/guidelines_helper.rb
module VoterRegistration
  module GuidelinesHelper
  end
end

app/helpers/voter_registration/home_helper.rb
module VoterRegistration
  module HomeHelper
  end
end

app/helpers/voter_registration/register_helper.rb
module VoterRegistration
  module RegisterHelper

    def help_text(instructions, field_name)
      unless instructions.nil?
        info = instructions.detect { |f| f[:name] == field_name }
        if info
          info.help_text
        end
      end
    end

    def title_select
      ["Mr.","Mrs.","Miss","Ms."]
    end

    def suffix_select
      ["Jr","Sr","II","III","IV"]
    end

  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VoterRegistration</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href='http://fonts.googleapis.com/css?family=Crimson+Text:600,400' rel='stylesheet' type='text/css'>
  <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '<%= ENV['GOOGLE_ANALYTICS'] %>']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

  </script>
</head>
<body data-spy="scroll" data-target=".sidebar" data-offset="50">
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to 'Voter Registration', root_path, :class=>"brand" %>
        <div class="nav-collapse">
          <ul class="nav">
            <li class=<%= 'active' if current_page?(root_path) %>><%= link_to 'Home', root_path %></li>
            <li class=<%= 'active' if params[:controller] == 'register' %>><%= link_to 'Register to Vote', register_index_path %></li>
            <li class=<%= 'active' if params[:controller] == 'guidelines' %>><%= link_to 'State Guidelines', guidelines_path %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>
  <div class="container">
    <%= render :partial => "layouts/flash", :locals => {:flash => flash} %>
    <%= yield %>
  </div> <!-- /container -->
  <footer class="footer">
    <div class="container">
      <p><%= link_to 'Terms of use', page_path(:id => "terms") %></p>
    </div>
  </footer>

</body>
</html>

app/views/layouts/voter_registration/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VoterRegistration</title>
  <%= stylesheet_link_tag    "voter_registration/application", :media => "all" %>
  <%= javascript_include_tag "voter_registration/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/voter_registration/guidelines/index.html.erb
<div class="page-header">
  <h1>State Guidelines</h1>
</div>
<p>Choose a state below to see specific voter registration guidelines.</p>
<div class="row">
  <div class="span4">
    <ul>
      <% @states[0..16].each do |state| %>
        <li><%= link_to state.name, guideline_path(state.state) %></li>
      <% end %>
    </ul>
  </div>
  <div class="span4">
    <ul>
      <% @states[17..33].each do |state| %>
        <li><%= link_to state.name, guideline_path(state.state) %></li>
      <% end %>
    </ul>
  </div>
  <div class="span4">
    <ul>
      <% @states[34..50].each do |state| %>
        <li><%= link_to state.name, guideline_path(state.state) %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/voter_registration/guidelines/show.html.erb
<div class="row">
  <div class="span3 sidebar">
    <ul class="nav nav-list sidenav affix">
      <li><a href="#registration">Registration</a><li>
      <li><a href="#deadline">Deadline</a></li>
      <li><a href="#felony">Felony Information</a></li>
      <li><a href="#students">Students</a></li>
      <li><a href="#identification">Identification</a></li>
      <li><a href="#same-day">Same Day</a></li>
      <li><a href="#early-vote">Early Vote</a></li>
    </ul>
  </div>

  <div class="span9">
    <div class="page-header">
      <h1> Guidelines in <%= @guidelines.name %> </h1>
    </div>
    <section id="registration">
    <h2> Voter Registration Requirements </h2>
    <div class="row">
      <div class="span9">
        <%= raw @guidelines.requirements %>
      </div>
    </div>
    </section>
    <section id="deadline">
    <h2> Registration Deadline </h2>
    <div class="row">
      <div class="span9">
        <%= raw @guidelines.deadline %>
      </div>
    </div>
    </section>
    <section id="felony">
    <h2> Felony Information </h2>
    <div class="row">
      <div class="span9">
        <%= raw @guidelines.felony %>
      </div>
    </div>
    </section>
    <section id="students">
    <h2> Information for Students </h2>
    <div class="row">
      <div class="span9">
        <%= raw @guidelines.student %>
      </div>
    </div>
    </section>
    <section id="identification">
    <h2> Identification Information </h2>
    <div class="row">
      <div class="span9">
        <%= raw @guidelines.identification %>
      </div>
    </div>
    </section>
    <section id="same-day">
    <h2> Same Day Registration </h2>
    <div class="row">
      <div class="span9">
        <%= raw @guidelines.same_day %>
      </div>
    </div>
    </section>
    <section id="early-vote">
    <h2> Early Voting Information </h2>
    <div class="row">
      <div class="span9">
        <%= raw @guidelines.early_voting %>
      </div>
    </div>
    </section>
    <section id="sos">
    <h2> Secretary of State </h2>
    <div class="row">
      <div class="span9">
        <%= link_to @guidelines.url, @guidelines.url, :target=>"_blank" %>
      </div>
    </div>
    </section>
  </div>
</div>

app/views/voter_registration/home/index.html.erb
<div class="hero-unit">
  <h1>Voter Registration</h1>
  <h2>Register to Vote in your state!</h2>
  <%= form_tag("", :method => "GET", :class => "form-inline") do %>
    <%= label_tag 'Select a state' %>
    <%= select_tag("state", options_for_select(Guidelines.all.collect {|s| [ s.name, s.state ] })) %>
    <%= submit_tag 'Go', :class=> "btn btn-primary" %>
  <% end %>
</div>
<div class="row">
  <div class="span12 section-header">
    <h1>About</h1>
  </div>
</div>
<div class="row">
  <div class="span4">
    <h2>Vote</h2>
    <p>We need more Americans to have a say in their government, not just the special interests.
    That's why we should be taking down roadblocks to voting.
    We believe in an America where everybody can make their voices heard.</p>
  </div>
  <div class="span4">
    <h2>How It Works</h2>
    <ol>
      <li>Choose a state</li>
      <li>Read the guidelines for the state</li>
      <li>Fill out the form</li>
      <li>Download your voter registration form</li>
      <li>Add a stamp and mail in your form</li>
    </ol>
  </div>
  <div class="span4">
    <h2>State Guidelines</h2>
    <p>Make sure you checkout the <%= link_to 'guidelines', vote.guidelines_path %> for your state</p>
  </div>
</div>

app/views/voter_registration/pages/terms.html.erb
<h2> Terms of Use </h2>
<div class="row">
  <div class="span12">
    <p>All information, dates and content included on this site are subject to change given the subject matter of the site.
    It is the responsibility of the user of the site here under to monitor changes in applicable law.
    Future versions of the site may include updated content to reflect any changes in applicable law.</p>
  </div>
</div>

app/views/voter_registration/register/_form.html.erb
<%= simple_form_for @register, :url => vote.register_create_path(@state), :html => { :class => 'form-horizontal' } do |f| %>
  <br/>
  <% if notification = f.error_notification %>
    <div class="alert alert-error fade in">
      <a class="close" data-dismiss="alert" href="#">&times;</a>
      <%= notification %>
    </div>
  <% end %>
  <p>Fill out the form below to generate a voter registration form</p>
  <section id="legal_name">
  <fieldset>
    <legend>Name</legend>
    <%= f.input :citizen do %>
      <%= f.check_box :citizen, :checked => "checked"  %> Are you a citizen of the United States of America?
    <% end %>
    <%= f.input :title, :collection => title_select %>
    <%= f.input :first_name %>
    <%= f.input :middle_name %>
    <%= f.input :last_name %>
    <%= f.input :name_suffix, :collection => suffix_select %>
  </fieldset>
  </section>
  <section id="home_address">
  <fieldset>
    <legend>Home Address</legend>
    <%= f.input :home_address %>
    <%= f.input :home_apt, :label => "Apt or Lot#" %>
    <%= f.input :home_city, :label => "City" %>
    <%= f.input :home_state, :label => "State" do %>
      <%= f.select(:home_state, options_for_select(Guidelines.all.collect {|s| [ s.name, s.state ] }, params[:state])) %>
    <% end %>
    <%= f.input :home_zip_code, :label => "ZIP code" %>
  </fieldset>
  </section>
  <section id="m-address">
  <legend>Mailing Address</legend>
  <div class="control-group">
    <div class="controls">
      <input type="checkbox" data-toggle="collapse" data-target="#mailing_address"/>  I have a different mailing address
    </div>
  </div>
  <div id="mailing_address" class="collapse out">
  <fieldset>
    <%= f.input :mailing_address %>
    <%= f.input :mailing_apt, :label => "Apt or Lot#" %>
    <%= f.input :mailing_city %>
    <%= f.input :mailing_state do %>
      <%= f.select(:mailing_state, options_for_select(Guidelines.all.collect {|s| [ s.name, s.state ] }), :include_blank => true) %>
    <% end %>
    <%= f.input :mailing_zip_code, :label => "Mailing ZIP code" %>
  </fieldset>
  </div>
  </section>
  <section id="p-address">
  <legend>Previous Address</legend>
  <div class="control-group">
    <div class="controls">
      <input type="checkbox" data-toggle="collapse" data-target="#previous_address"/>   I have recently moved
    </div>
  </div>
  <div id="previous_address" class="collapse out">
  <fieldset>
    <%= f.input :previous_address %>
    <%= f.input :previous_apt, :label => "Apt or Lot#"  %>
    <%= f.input :previous_city %>
    <%= f.input(:previous_state) do %>
      <%= f.select(:previous_state, options_for_select(Guidelines.all.collect {|s| [ s.name, s.state ] }), :include_blank => true) %>
    <% end %>
    <%= f.input :previous_zip_code, :label => "Previous ZIP code" %>
  </fieldset>
  </div>
  </section>
  <section id="p-name">
  <legend>Previous Name</legend>
  <div class="control-group">
    <div class="controls">
      <input type="checkbox" data-toggle="collapse" data-target="#previous_name"/>   I have recently changed my name
    </div>
  </div>
  <div id="previous_name" class="collapse out">
  <fieldset>
    <%= f.input :previous_title, :collection => title_select, :label => "Title" %>
    <%= f.input :previous_first_name, :label => "First name" %>
    <%= f.input :previous_middle_name, :label => "Middle name" %>
    <%= f.input :previous_last_name, :label => "Last name" %>
    <%= f.input :previous_suffix, :collection => suffix_select, :lavel => "Suffix" %>
  </fieldset>
  </div>
  </section>
  <section id="identification">
  <fieldset>
    <legend>Identification</legend>
    <%= f.input :date_of_birth, :as => :date, :start_year => Date.today.year - 100,
                              :end_year => Date.today.year - 17,
                              :order => [:month, :day, :year],
                              :default => {:month => 1, :day => 1, :year => Date.today.year - 50} %>
    <%= f.input :phone %>
    <%= f.input :id_number, :hint => help_text(@instructions, "id_number") %>
  </fieldset>
  <fieldset id="additional">
    <legend>Additional Information</legend>
    <%= f.input :political_party, :collection => PoliticalParty.pluck(:name), :hint => help_text(@instructions,"political_party")  %>
    <%= f.input :ethnicity, :collection => Ethnicity.pluck(:name), :hint => help_text(@instructions, "ethnicity") %>
  </fieldset>
  </section>
  <div class="form-actions">
    <%= f.submit "Submit", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/voter_registration/register/complete.html.erb
<div class="row">
  <div class="span11">
    <br/>
    <p>Congratulations! You’ve completed your voter registration form.</p>
    <%= link_to "Download Voter Registration Form (PDF)", register_complete_path(format: "pdf") , :class => "btn-large btn-success" %>
  </div>
</div>
<br/>

<h2> Registration Deadlines </h2>
<div class="row">
  <div class="span10">
    <%= raw @state_info.deadline %>
  </div>
</div>

<h2> Registration Guidelines </h2>
<div class="row">
  <div class="span10">
    <%= raw @state_info.requirements %>
  </div>
</div>

app/views/voter_registration/register/index.html.erb
<div class="page-header">
  <h1>Register to Vote</h1>
</div>
<div class="row">
  <div class="span11">
    <%= form_tag(register_index_path, :method => "GET", :class => "well form-inline") do %>
      <%= label_tag 'Select a state' %>
      <%= select_tag("state", options_for_select(Guidelines.all.collect {|s| [ s.name, s.state ] })) %>
      <%= submit_tag 'Go', :class=> "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/voter_registration/register/new.html.erb
<div class="row">
  <div class="span3 sidebar">
    <ul class="nav nav-list sidenav affix">
      <li><a href="#legal_name">Name</a><li>
      <li><a href="#home_address">Home Address</a></li>
      <li><a href="#m-address">Mailing Address</a></li>
      <li><a href="#p-address">Previous Address</a></li>
      <li><a href="#p-name">Previous Name</a></li>
      <li><a href="#identification">Identification</a></li>
      <li><a href="#additional">Additional Information</a></li>
    </ul>
  </div>
  <div class="span9">
    <div class="page-header">
      <h1>Register in <%= @guidelines.name %></h1>
    </div>
    <% if @guidelines.supported %>
      <% if @guidelines.online? && !@register.errors.any?%>
        <h2><%= @guidelines.name %> offers online registration</h2>
        <h4>To register to vote online in <%= @guidelines.name %>, you must:</h4>
        <%= raw @guidelines.online_requirements %>
        <p>Register online here: <%= link_to @guidelines.online_url, @guidelines.online_url %>
        <h4>OR</h4>
        <p>Continue filling out the form below for registration by mail</p>
      <% end %>
     <% if ENV['TWITTER_KEY'] %>
        <br/>
        <%= link_to image_tag('sign-in-with-twitter-d.png'), '/auth/twitter' %>
      <% end %>
      <br/>
      <%= render 'form' %>
    <% else %>
      <%= raw @guidelines.unsupported %>
    <% end  %>
  </div>
</div>